
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package Generado.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int palabraReservada = 3;
  public static final int wwhile = 27;
  public static final int opMultiplicacion = 37;
  public static final int bbreak = 33;
  public static final int CHAR = 6;
  public static final int opNot = 44;
  public static final int opAnd = 42;
  public static final int ffinally = 32;
  public static final int dosPuntos = 45;
  public static final int opComparadores = 9;
  public static final int opDivision = 38;
  public static final int coma = 49;
  public static final int range = 26;
  public static final int INT = 4;
  public static final int cuadradoAbierto = 51;
  public static final int identificador = 2;
  public static final int iinput = 29;
  public static final int parenAbierto = 47;
  public static final int opAsignaciones = 10;
  public static final int clas = 17;
  public static final int ccontinue = 34;
  public static final int def = 18;
  public static final int opModulo = 40;
  public static final int ttrue = 20;
  public static final int ffalse = 19;
  public static final int var = 16;
  public static final int opDelimitadores = 11;
  public static final int EOF = 0;
  public static final int opBits = 12;
  public static final int iif = 21;
  public static final int error = 1;
  public static final int opLogicos = 13;
  public static final int opSuma = 35;
  public static final int opDivisionE = 39;
  public static final int in = 25;
  public static final int punto = 52;
  public static final int opOr = 43;
  public static final int elif = 23;
  public static final int ffor = 24;
  public static final int ERROR = 14;
  public static final int pprint = 28;
  public static final int puntoComa = 46;
  public static final int ttry = 30;
  public static final int eexcept = 31;
  public static final int eelse = 22;
  public static final int FLOAT = 5;
  public static final int cuadradoCerrado = 50;
  public static final int END = 15;
  public static final int opAritmeticos = 8;
  public static final int STRING = 7;
  public static final int parenCerrado = 48;
  public static final int opResta = 36;
  public static final int opPotencia = 41;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "identificador",
  "palabraReservada",
  "INT",
  "FLOAT",
  "CHAR",
  "STRING",
  "opAritmeticos",
  "opComparadores",
  "opAsignaciones",
  "opDelimitadores",
  "opBits",
  "opLogicos",
  "ERROR",
  "END",
  "var",
  "clas",
  "def",
  "ffalse",
  "ttrue",
  "iif",
  "eelse",
  "elif",
  "ffor",
  "in",
  "range",
  "wwhile",
  "pprint",
  "iinput",
  "ttry",
  "eexcept",
  "ffinally",
  "bbreak",
  "ccontinue",
  "opSuma",
  "opResta",
  "opMultiplicacion",
  "opDivision",
  "opDivisionE",
  "opModulo",
  "opPotencia",
  "opAnd",
  "opOr",
  "opNot",
  "dosPuntos",
  "puntoComa",
  "parenAbierto",
  "parenCerrado",
  "coma",
  "cuadradoCerrado",
  "cuadradoAbierto",
  "punto"
  };
}

