/* The following code was generated by JFlex 1.6.1 */

package Generado.Scanner;
import static Generado.Scanner.Token.*;
import Generado.Parser.sym;
import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/Generado/Scanner/lexer.flex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int MYSTRING = 2;
  public static final int MYCHAR = 4;
  public static final int COMENTARIOBLOQUE = 6;
  public static final int COMENTARIOBLOQUE2 = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\71\1\11\1\13\1\14\1\14\1\12\22\71\1\10\1\52\1\16"+
    "\1\15\1\71\1\50\1\55\1\64\1\56\1\57\1\46\1\45\1\6"+
    "\1\45\1\60\1\47\1\3\1\4\6\5\2\2\1\61\1\63\1\53"+
    "\1\51\1\54\2\71\1\1\1\65\13\1\1\44\1\66\10\1\1\67"+
    "\2\1\1\62\1\72\1\62\1\55\1\1\1\71\1\25\1\31\1\33"+
    "\1\7\1\32\1\22\1\30\1\34\1\17\1\1\1\35\1\23\1\42"+
    "\1\20\1\24\1\40\1\1\1\27\1\26\1\21\1\36\1\1\1\43"+
    "\1\37\1\41\1\1\1\62\1\55\1\62\1\55\1\71\5\70\1\73"+
    "\32\70\1\0\u15df\70\1\0\u097f\70\13\0\35\70\1\73\1\73\5\70"+
    "\1\0\57\70\1\0\u0fa0\70\1\0\uffff\70\uffff\70\uffff\70\uffff\70\uffff\70\uffff\70\uffff\70\uffff\70\uffff\70\uffff\70\uffff\70\uffff\70\uffff\70\uffff\70\uffff\70\uffff\70\ud00f\70";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\2\2\3\1\4\1\2\3\5\1\6"+
    "\20\2\4\7\1\10\1\1\2\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\2\24"+
    "\1\25\1\21\1\26\2\27\2\21\1\30\1\31\1\0"+
    "\3\31\1\2\1\0\2\32\11\2\1\33\21\2\1\10"+
    "\1\11\1\0\1\34\1\35\1\36\2\0\1\37\3\3"+
    "\1\40\1\41\1\42\27\2\1\43\1\44\22\2\1\45"+
    "\3\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\74\0\170\0\264\0\360\0\u012c\0\u0168\0\u01a4"+
    "\0\u01e0\0\u012c\0\u021c\0\u012c\0\u0258\0\u0294\0\u02d0\0\u030c"+
    "\0\u0348\0\u0384\0\u03c0\0\u03fc\0\u0438\0\u0474\0\u04b0\0\u04ec"+
    "\0\u0528\0\u0564\0\u05a0\0\u05dc\0\u0618\0\u0654\0\u0690\0\u06cc"+
    "\0\u0708\0\u0744\0\u012c\0\u0780\0\u0780\0\u07bc\0\u07f8\0\u012c"+
    "\0\u012c\0\u012c\0\u012c\0\u012c\0\u012c\0\u0834\0\u012c\0\u012c"+
    "\0\u012c\0\u0870\0\u012c\0\u012c\0\u08ac\0\u012c\0\u012c\0\u08e8"+
    "\0\u0924\0\u0960\0\u099c\0\u09d8\0\u0a14\0\u0a50\0\u0a8c\0\u0ac8"+
    "\0\u0b04\0\u0b40\0\u0b7c\0\u0168\0\u0bb8\0\u0bf4\0\u0c30\0\u0c6c"+
    "\0\u0ca8\0\u0ce4\0\u0d20\0\u0d5c\0\u0d98\0\u0168\0\u0dd4\0\u0e10"+
    "\0\u0e4c\0\u0e88\0\u0ec4\0\u0f00\0\u0f3c\0\u0f78\0\u0fb4\0\u0ff0"+
    "\0\u102c\0\u1068\0\u10a4\0\u10e0\0\u111c\0\u1158\0\u1194\0\u012c"+
    "\0\u012c\0\u11d0\0\u012c\0\u012c\0\u012c\0\u120c\0\u1248\0\u0a14"+
    "\0\u0a50\0\u0a8c\0\u0ac8\0\u0168\0\u012c\0\u0168\0\u1284\0\u12c0"+
    "\0\u12fc\0\u1338\0\u0b7c\0\u1374\0\u13b0\0\u13ec\0\u1428\0\u1464"+
    "\0\u14a0\0\u14dc\0\u1518\0\u1554\0\u1590\0\u15cc\0\u1608\0\u1644"+
    "\0\u1680\0\u16bc\0\u16f8\0\u1734\0\u1770\0\u012c\0\u012c\0\u17ac"+
    "\0\u17e8\0\u1824\0\u1860\0\u189c\0\u18d8\0\u1914\0\u1950\0\u198c"+
    "\0\u19c8\0\u1a04\0\u1a40\0\u1a7c\0\u1ab8\0\u1af4\0\u1b30\0\u1b6c"+
    "\0\u1ba8\0\u0168\0\u1be4\0\u1c20\0\u1c5c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\1\10\1\11\2\10\1\12\1\13\2\14"+
    "\1\15\1\14\1\0\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\4\7\1\35\2\7\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\53\1\55\1\56\3\7"+
    "\3\6\1\0\1\6\7\57\1\60\1\61\1\62\1\63"+
    "\1\0\1\57\1\64\53\57\1\65\1\0\64\57\1\66"+
    "\7\57\1\67\7\57\1\60\1\67\1\70\2\67\1\57"+
    "\1\71\53\57\1\65\2\67\7\57\1\60\1\67\1\70"+
    "\2\67\47\57\1\72\5\57\1\65\1\67\74\0\1\73"+
    "\5\7\1\0\1\7\7\0\26\7\20\0\3\7\1\73"+
    "\2\0\1\73\1\0\1\74\4\10\1\0\1\74\7\0"+
    "\26\74\13\0\1\75\4\0\3\74\5\0\1\74\4\10"+
    "\1\0\1\74\7\0\5\74\1\76\4\74\1\77\5\74"+
    "\1\100\5\74\13\0\1\75\4\0\1\77\1\76\1\100"+
    "\4\0\1\73\5\7\1\0\1\7\7\0\13\7\1\101"+
    "\12\7\20\0\3\7\1\73\2\0\1\73\13\0\1\14"+
    "\60\0\12\16\1\15\1\14\60\16\16\0\1\102\55\0"+
    "\1\73\5\7\1\0\1\7\7\0\1\7\1\103\1\7"+
    "\1\104\3\7\1\104\13\7\1\105\2\7\20\0\3\7"+
    "\1\73\2\0\2\73\5\7\1\0\1\7\7\0\5\7"+
    "\1\106\20\7\20\0\3\7\1\73\2\0\2\73\5\7"+
    "\1\0\1\7\7\0\10\7\1\107\15\7\20\0\3\7"+
    "\1\73\2\0\2\73\5\7\1\0\1\7\7\0\1\110"+
    "\3\7\1\111\1\112\2\7\1\113\15\7\20\0\3\7"+
    "\1\73\2\0\2\73\5\7\1\0\1\7\7\0\1\114"+
    "\5\7\1\115\17\7\20\0\3\7\1\73\2\0\2\73"+
    "\5\7\1\0\1\7\7\0\10\7\1\116\15\7\20\0"+
    "\3\7\1\73\2\0\2\73\5\7\1\0\1\7\7\0"+
    "\1\7\1\117\5\7\1\120\16\7\20\0\3\7\1\73"+
    "\2\0\2\73\5\7\1\0\1\7\7\0\2\7\1\121"+
    "\23\7\20\0\3\7\1\73\2\0\2\73\5\7\1\0"+
    "\1\7\7\0\6\7\1\122\4\7\1\123\12\7\20\0"+
    "\3\7\1\73\2\0\2\73\5\7\1\0\1\7\7\0"+
    "\4\7\1\124\21\7\20\0\3\7\1\73\2\0\2\73"+
    "\5\7\1\0\1\7\7\0\5\7\1\125\2\7\1\126"+
    "\15\7\20\0\3\7\1\73\2\0\2\73\5\7\1\0"+
    "\1\7\7\0\4\7\1\127\13\7\1\130\5\7\20\0"+
    "\3\7\1\73\2\0\2\73\5\7\1\0\1\7\7\0"+
    "\4\7\1\131\1\132\7\7\1\133\10\7\20\0\3\7"+
    "\1\73\2\0\2\73\5\7\1\0\1\7\7\0\6\7"+
    "\1\134\1\7\1\135\15\7\20\0\3\7\1\73\2\0"+
    "\2\73\5\7\1\0\1\7\7\0\15\7\1\136\10\7"+
    "\20\0\3\7\1\73\2\0\2\73\5\7\1\0\1\7"+
    "\7\0\5\7\1\137\20\7\20\0\3\7\1\73\2\0"+
    "\1\73\51\0\1\140\70\0\1\40\2\0\1\140\71\0"+
    "\1\40\1\0\1\140\73\0\1\141\73\0\1\141\1\0"+
    "\1\50\1\141\70\0\1\141\2\0\1\50\103\0\1\142"+
    "\22\0\1\63\76\0\1\143\1\0\1\144\1\61\5\0"+
    "\1\145\57\0\1\67\76\0\1\146\141\0\1\147\7\0"+
    "\6\73\1\0\1\73\7\0\26\73\20\0\4\73\2\0"+
    "\1\73\1\0\5\74\1\0\1\74\7\0\26\74\20\0"+
    "\3\74\6\0\4\150\67\0\2\74\3\151\1\0\1\74"+
    "\7\0\26\74\20\0\3\74\5\0\2\74\2\152\1\74"+
    "\1\0\1\74\7\0\26\74\20\0\3\74\5\0\1\74"+
    "\4\153\1\0\1\153\7\0\3\74\1\153\2\74\1\153"+
    "\3\74\3\153\11\74\20\0\3\74\4\0\1\73\5\7"+
    "\1\0\1\7\7\0\3\7\1\154\1\104\21\7\20\0"+
    "\3\7\1\73\2\0\1\73\16\0\1\155\55\0\1\73"+
    "\5\7\1\0\1\7\7\0\2\7\1\156\23\7\20\0"+
    "\3\7\1\73\2\0\2\73\5\7\1\0\1\7\7\0"+
    "\21\7\1\157\4\7\20\0\3\7\1\73\2\0\2\73"+
    "\5\7\1\0\1\7\7\0\2\7\1\116\23\7\20\0"+
    "\3\7\1\73\2\0\2\73\5\7\1\0\1\7\7\0"+
    "\22\7\1\104\3\7\20\0\3\7\1\73\2\0\2\73"+
    "\5\7\1\0\1\7\7\0\1\7\1\160\24\7\20\0"+
    "\3\7\1\73\2\0\2\73\5\7\1\0\1\7\7\0"+
    "\5\7\1\161\20\7\20\0\3\7\1\73\2\0\2\73"+
    "\5\7\1\0\1\7\7\0\10\7\1\104\15\7\20\0"+
    "\3\7\1\73\2\0\2\73\5\7\1\0\1\7\7\0"+
    "\5\7\1\162\20\7\20\0\3\7\1\73\2\0\2\73"+
    "\5\7\1\0\1\7\7\0\7\7\1\163\16\7\20\0"+
    "\3\7\1\73\2\0\2\73\5\7\1\0\1\7\7\0"+
    "\23\7\1\164\2\7\20\0\3\7\1\73\2\0\2\73"+
    "\5\7\1\0\1\116\7\0\26\7\20\0\3\7\1\73"+
    "\2\0\2\73\5\7\1\0\1\7\7\0\7\7\1\165"+
    "\16\7\20\0\3\7\1\73\2\0\2\73\5\7\1\0"+
    "\1\7\7\0\10\7\1\166\15\7\20\0\3\7\1\73"+
    "\2\0\2\73\5\7\1\0\1\7\7\0\1\167\25\7"+
    "\20\0\3\7\1\73\2\0\2\73\5\7\1\0\1\7"+
    "\7\0\2\7\1\170\23\7\20\0\3\7\1\73\2\0"+
    "\2\73\5\7\1\0\1\7\7\0\5\7\1\171\20\7"+
    "\20\0\3\7\1\73\2\0\2\73\5\7\1\0\1\7"+
    "\7\0\5\7\1\172\20\7\20\0\3\7\1\73\2\0"+
    "\2\73\5\7\1\0\1\7\7\0\13\7\1\173\12\7"+
    "\20\0\3\7\1\73\2\0\2\73\5\7\1\0\1\7"+
    "\7\0\1\174\6\7\1\175\16\7\20\0\3\7\1\73"+
    "\2\0\2\73\5\7\1\0\1\7\7\0\13\7\1\176"+
    "\1\177\11\7\20\0\3\7\1\73\2\0\2\73\5\7"+
    "\1\0\1\7\7\0\6\7\1\200\17\7\20\0\3\7"+
    "\1\73\2\0\2\73\5\7\1\0\1\7\7\0\1\7"+
    "\1\201\24\7\20\0\3\7\1\73\2\0\2\73\5\7"+
    "\1\0\1\7\7\0\6\7\1\202\17\7\20\0\3\7"+
    "\1\73\2\0\2\73\5\7\1\0\1\7\7\0\7\7"+
    "\1\203\16\7\20\0\3\7\1\73\2\0\2\73\5\7"+
    "\1\0\1\7\7\0\1\204\25\7\20\0\3\7\1\73"+
    "\2\0\2\73\5\7\1\0\1\7\7\0\1\205\25\7"+
    "\20\0\3\7\1\73\2\0\2\73\5\7\1\0\1\7"+
    "\7\0\1\7\1\175\24\7\20\0\3\7\1\73\2\0"+
    "\1\73\64\0\1\206\25\0\1\207\141\0\1\207\7\0"+
    "\1\73\5\7\1\0\1\7\7\0\5\7\1\210\20\7"+
    "\20\0\3\7\1\73\2\0\2\73\5\7\1\0\1\7"+
    "\7\0\6\7\1\211\17\7\20\0\3\7\1\73\2\0"+
    "\2\73\5\7\1\0\1\7\7\0\6\7\1\163\17\7"+
    "\20\0\3\7\1\73\2\0\2\73\5\7\1\0\1\7"+
    "\7\0\23\7\1\104\2\7\20\0\3\7\1\73\2\0"+
    "\2\73\5\7\1\0\1\7\7\0\12\7\1\212\13\7"+
    "\20\0\3\7\1\73\2\0\2\73\5\7\1\0\1\7"+
    "\7\0\13\7\1\210\12\7\20\0\3\7\1\73\2\0"+
    "\2\73\5\7\1\0\1\7\7\0\1\213\25\7\20\0"+
    "\3\7\1\73\2\0\2\73\5\7\1\0\1\7\7\0"+
    "\7\7\1\175\16\7\20\0\3\7\1\73\2\0\2\73"+
    "\5\7\1\0\1\7\7\0\17\7\1\214\6\7\20\0"+
    "\3\7\1\73\2\0\2\73\5\7\1\0\1\7\7\0"+
    "\12\7\1\215\13\7\20\0\3\7\1\73\2\0\2\73"+
    "\5\7\1\0\1\7\7\0\4\7\1\216\21\7\20\0"+
    "\3\7\1\73\2\0\2\73\5\7\1\0\1\7\7\0"+
    "\6\7\1\217\17\7\20\0\3\7\1\73\2\0\2\73"+
    "\5\7\1\0\1\7\7\0\3\7\1\104\22\7\20\0"+
    "\3\7\1\73\2\0\2\73\5\7\1\0\1\7\7\0"+
    "\13\7\1\104\12\7\20\0\3\7\1\73\2\0\2\73"+
    "\5\7\1\0\1\7\7\0\14\7\1\104\11\7\20\0"+
    "\3\7\1\73\2\0\2\73\5\7\1\0\1\7\7\0"+
    "\13\7\1\220\12\7\20\0\3\7\1\73\2\0\2\73"+
    "\5\7\1\0\1\7\7\0\7\7\1\221\16\7\20\0"+
    "\3\7\1\73\2\0\2\73\5\7\1\0\1\7\7\0"+
    "\2\7\1\222\23\7\20\0\3\7\1\73\2\0\2\73"+
    "\5\7\1\0\1\7\7\0\10\7\1\156\15\7\20\0"+
    "\3\7\1\73\2\0\2\73\5\7\1\0\1\7\7\0"+
    "\7\7\1\104\16\7\20\0\3\7\1\73\2\0\2\73"+
    "\5\7\1\0\1\7\7\0\1\7\1\223\24\7\20\0"+
    "\3\7\1\73\2\0\2\73\5\7\1\0\1\7\7\0"+
    "\4\7\1\175\21\7\20\0\3\7\1\73\2\0\2\73"+
    "\5\7\1\0\1\7\7\0\10\7\1\223\15\7\20\0"+
    "\3\7\1\73\2\0\2\73\5\7\1\0\1\7\7\0"+
    "\4\7\1\224\21\7\20\0\3\7\1\73\2\0\2\73"+
    "\5\7\1\0\1\225\7\0\26\7\20\0\3\7\1\73"+
    "\2\0\2\73\5\7\1\0\1\7\7\0\1\7\1\226"+
    "\24\7\20\0\3\7\1\73\2\0\2\73\5\7\1\0"+
    "\1\7\7\0\10\7\1\227\15\7\20\0\3\7\1\73"+
    "\2\0\2\73\5\7\1\0\1\7\7\0\6\7\1\230"+
    "\17\7\20\0\3\7\1\73\2\0\2\73\5\7\1\0"+
    "\1\7\7\0\13\7\1\231\12\7\20\0\3\7\1\73"+
    "\2\0\2\73\5\7\1\0\1\7\7\0\16\7\1\104"+
    "\7\7\20\0\3\7\1\73\2\0\2\73\5\7\1\0"+
    "\1\7\7\0\21\7\1\223\4\7\20\0\3\7\1\73"+
    "\2\0\2\73\5\7\1\0\1\7\7\0\7\7\1\232"+
    "\16\7\20\0\3\7\1\73\2\0\2\73\5\7\1\0"+
    "\1\7\7\0\1\233\25\7\20\0\3\7\1\73\2\0"+
    "\2\73\5\7\1\0\1\7\7\0\2\7\1\104\23\7"+
    "\20\0\3\7\1\73\2\0\2\73\5\7\1\0\1\7"+
    "\7\0\4\7\1\107\21\7\20\0\3\7\1\73\2\0"+
    "\2\73\5\7\1\0\1\7\7\0\6\7\1\104\17\7"+
    "\20\0\3\7\1\73\2\0\2\73\5\7\1\0\1\7"+
    "\7\0\11\7\1\156\14\7\20\0\3\7\1\73\2\0"+
    "\2\73\5\7\1\0\1\7\7\0\1\7\1\104\24\7"+
    "\20\0\3\7\1\73\2\0\2\73\5\7\1\0\1\7"+
    "\7\0\4\7\1\104\21\7\20\0\3\7\1\73\2\0"+
    "\2\73\5\7\1\0\1\7\7\0\6\7\1\234\17\7"+
    "\20\0\3\7\1\73\2\0\2\73\5\7\1\0\1\7"+
    "\7\0\1\7\1\235\24\7\20\0\3\7\1\73\2\0"+
    "\2\73\5\7\1\0\1\7\7\0\1\7\1\156\24\7"+
    "\20\0\3\7\1\73\2\0\2\73\5\7\1\0\1\7"+
    "\7\0\17\7\1\175\6\7\20\0\3\7\1\73\2\0"+
    "\1\73";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7320];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\1\11\3\1\1\11\1\1\1\11\26\1\1\11"+
    "\4\1\6\11\1\1\3\11\1\1\2\11\1\1\2\11"+
    "\5\1\1\0\4\1\1\0\35\1\2\11\1\0\3\11"+
    "\2\0\5\1\1\11\30\1\2\11\26\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //esto se copia directamente

    StringBuffer string = new StringBuffer();
    Boolean cambioLinea = false;

    public String lexeme;
    public int getLine(){
        return yyline;
    }

    private Symbol symbol(int type) {
        return new Symbol(type, yyline+1, yycolumn+1);
    }
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline+1, yycolumn+1, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 224) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case MYSTRING: {
              yybegin(YYINITIAL); lexeme = "String sin terminar: " + string.toString(); return symbol(sym.ERROR);
            }
            case 158: break;
            case MYCHAR: {
              yybegin(YYINITIAL); lexeme = "Char sin terminar: " + string.toString(); return symbol(sym.ERROR);
            }
            case 159: break;
            case COMENTARIOBLOQUE: {
              yybegin(YYINITIAL); lexeme = "Comentario de bloque sin terminar: " + "\"\"\"" + string.toString(); return symbol(sym.ERROR, lexeme);
            }
            case 160: break;
            case COMENTARIOBLOQUE2: {
              yybegin(YYINITIAL); lexeme = "Comentario de bloque sin terminar: " + "\'\'\'" + string.toString(); return symbol(sym.ERROR, lexeme);
            }
            case 161: break;
            default:
          {   return new java_cup.runtime.Symbol(sym.EOF);
 }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexeme = yytext();return symbol(sym.ERROR, lexeme);
            }
          case 38: break;
          case 2: 
            { lexeme=yytext(); return symbol(sym.identificador, lexeme);
            }
          case 39: break;
          case 3: 
            { lexeme=yytext(); return symbol(sym.INT, lexeme);
            }
          case 40: break;
          case 4: 
            { lexeme = yytext(); return symbol(sym.coma, lexeme);
            }
          case 41: break;
          case 5: 
            { /* ignore */
            }
          case 42: break;
          case 6: 
            { string.setLength(0); cambioLinea = false; yybegin(MYSTRING);
            }
          case 43: break;
          case 7: 
            { lexeme = yytext(); return symbol(sym.opAritmeticos, lexeme);
            }
          case 44: break;
          case 8: 
            { lexeme = yytext(); return symbol(sym.opAsignaciones, lexeme);
            }
          case 45: break;
          case 9: 
            { lexeme = yytext(); return symbol(sym.opComparadores, lexeme);
            }
          case 46: break;
          case 10: 
            { lexeme = yytext(); return symbol(sym.opBits, lexeme);
            }
          case 47: break;
          case 11: 
            { lexeme = yytext(); return symbol(sym.parenAbierto, lexeme);
            }
          case 48: break;
          case 12: 
            { lexeme = yytext(); return symbol(sym.parenCerrado, lexeme);
            }
          case 49: break;
          case 13: 
            { lexeme = yytext(); return symbol(sym.opDelimitadores, lexeme);
            }
          case 50: break;
          case 14: 
            { lexeme = yytext(); return symbol(sym.dosPuntos, lexeme);
            }
          case 51: break;
          case 15: 
            { lexeme = yytext(); return symbol(sym.puntoComa, lexeme);
            }
          case 52: break;
          case 16: 
            { string.setLength(0); yybegin(MYCHAR);
            }
          case 53: break;
          case 17: 
            { string.append( yytext() );
            }
          case 54: break;
          case 18: 
            { string.append(' ');
            }
          case 55: break;
          case 19: 
            { string.append('\t');
            }
          case 56: break;
          case 20: 
            { cambioLinea = true; string.append('\n');
            }
          case 57: break;
          case 21: 
            { yybegin(YYINITIAL);
                                     lexeme = "\"" +string.toString()+"\"";
                                     if(cambioLinea){
                                          return symbol(sym.ERROR, lexeme);
                                     }else{
                                          return symbol(sym.STRING, lexeme);
                                     }
            }
          case 58: break;
          case 22: 
            { yybegin(YYINITIAL); lexeme = "'"+ string.toString()+"'"; 
                                     if(string.length()>1)
                                        return symbol(sym.ERROR, lexeme);
                                     else
                                        return symbol(sym.CHAR, lexeme);
            }
          case 59: break;
          case 23: 
            { string.append(yytext());
            }
          case 60: break;
          case 24: 
            { lexeme=yytext(); return symbol(sym.ERROR, lexeme);
            }
          case 61: break;
          case 25: 
            { lexeme = yytext(); return symbol(sym.INT, lexeme);
            }
          case 62: break;
          case 26: 
            { lexeme = yytext(); return symbol(sym.palabraReservada, lexeme);
            }
          case 63: break;
          case 27: 
            { lexeme = yytext(); return symbol(sym.opLogicos, lexeme);
            }
          case 64: break;
          case 28: 
            { string.append('\"');
            }
          case 65: break;
          case 29: 
            { string.append('\n');
            }
          case 66: break;
          case 30: 
            { string.append('\r');
            }
          case 67: break;
          case 31: 
            { lexeme=yytext(); return symbol(sym.FLOAT, lexeme);
            }
          case 68: break;
          case 32: 
            { lexeme = yytext(); return symbol(sym.def, lexeme);
            }
          case 69: break;
          case 33: 
            { string.setLength(0); yybegin(COMENTARIOBLOQUE);
            }
          case 70: break;
          case 34: 
            { lexeme = yytext(); return symbol(sym.var, lexeme);
            }
          case 71: break;
          case 35: 
            { string.setLength(0); yybegin(COMENTARIOBLOQUE2);
            }
          case 72: break;
          case 36: 
            { yybegin(YYINITIAL);
            }
          case 73: break;
          case 37: 
            { lexeme = yytext(); return symbol(sym.clas, lexeme);
            }
          case 74: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
