/* The following code was generated by JFlex 1.6.1 */

package Generado.Scanner;
import static Generado.Scanner.Token.*;
import Generado.Parser.sym;
import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/Generado/Scanner/lexer.flex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int MYSTRING = 2;
  public static final int MYCHAR = 4;
  public static final int COMENTARIOBLOQUE = 6;
  public static final int COMENTARIOBLOQUE2 = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\65\1\11\1\13\1\14\1\14\1\12\22\65\1\10\1\52\1\16"+
    "\1\15\1\65\1\50\1\55\1\60\1\6\1\6\1\46\1\45\1\6"+
    "\1\45\1\56\1\47\1\3\1\4\6\5\2\2\1\57\1\65\1\53"+
    "\1\51\1\54\2\65\1\1\1\61\13\1\1\44\1\62\10\1\1\63"+
    "\2\1\1\6\1\66\1\6\1\55\1\1\1\65\1\25\1\31\1\33"+
    "\1\7\1\32\1\22\1\30\1\34\1\17\1\1\1\35\1\23\1\42"+
    "\1\20\1\24\1\40\1\1\1\27\1\26\1\21\1\36\1\1\1\43"+
    "\1\37\1\41\1\1\1\6\1\55\1\6\1\55\1\65\5\64\1\67"+
    "\32\64\1\0\u15df\64\1\0\u097f\64\13\0\35\64\1\67\1\67\5\64"+
    "\1\0\57\64\1\0\u0fa0\64\1\0\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\ud00f\64";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\2\2\3\1\4\1\2\3\5\1\6"+
    "\20\2\4\7\1\10\1\1\2\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\2\20\1\21\1\15\1\22\2\23"+
    "\2\15\1\24\1\25\1\0\3\25\1\2\1\0\2\26"+
    "\11\2\1\27\21\2\1\10\1\11\1\0\1\30\1\31"+
    "\1\32\2\0\1\33\3\3\1\34\1\35\27\2\1\36"+
    "\1\37\22\2\1\40\3\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\340\0\u0118\0\u0150\0\u0188"+
    "\0\u01c0\0\u0118\0\u01f8\0\u0118\0\u0230\0\u0268\0\u02a0\0\u02d8"+
    "\0\u0310\0\u0348\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460\0\u0498"+
    "\0\u04d0\0\u0508\0\u0540\0\u0578\0\u05b0\0\u05e8\0\u0620\0\u0658"+
    "\0\u0690\0\u06c8\0\u0118\0\u0700\0\u0700\0\u0738\0\u0770\0\u0118"+
    "\0\u0118\0\u07a8\0\u0118\0\u0118\0\u0118\0\u07e0\0\u0118\0\u0118"+
    "\0\u0818\0\u0118\0\u0118\0\u0850\0\u0888\0\u08c0\0\u08f8\0\u0930"+
    "\0\u0968\0\u09a0\0\u09d8\0\u0a10\0\u0a48\0\u0a80\0\u0ab8\0\u0150"+
    "\0\u0af0\0\u0b28\0\u0b60\0\u0b98\0\u0bd0\0\u0c08\0\u0c40\0\u0c78"+
    "\0\u0cb0\0\u0150\0\u0ce8\0\u0d20\0\u0d58\0\u0d90\0\u0dc8\0\u0e00"+
    "\0\u0e38\0\u0e70\0\u0ea8\0\u0ee0\0\u0f18\0\u0f50\0\u0f88\0\u0fc0"+
    "\0\u0ff8\0\u1030\0\u1068\0\u0118\0\u0118\0\u10a0\0\u0118\0\u0118"+
    "\0\u0118\0\u10d8\0\u1110\0\u0968\0\u09a0\0\u09d8\0\u0a10\0\u0118"+
    "\0\u0150\0\u1148\0\u1180\0\u11b8\0\u11f0\0\u0ab8\0\u1228\0\u1260"+
    "\0\u1298\0\u12d0\0\u1308\0\u1340\0\u1378\0\u13b0\0\u13e8\0\u1420"+
    "\0\u1458\0\u1490\0\u14c8\0\u1500\0\u1538\0\u1570\0\u15a8\0\u15e0"+
    "\0\u0118\0\u0118\0\u1618\0\u1650\0\u1688\0\u16c0\0\u16f8\0\u1730"+
    "\0\u1768\0\u17a0\0\u17d8\0\u1810\0\u1848\0\u1880\0\u18b8\0\u18f0"+
    "\0\u1928\0\u1960\0\u1998\0\u19d0\0\u0150\0\u1a08\0\u1a40\0\u1a78";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\1\10\1\11\2\10\1\12\1\13\2\14"+
    "\1\15\1\14\1\0\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\4\7\1\35\2\7\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\12\1\51\1\52\3\7\3\6\1\0\1\6\7\53"+
    "\1\54\1\55\1\56\1\57\1\0\1\53\1\60\47\53"+
    "\1\61\1\0\60\53\1\62\7\53\1\63\7\53\1\54"+
    "\1\63\1\64\2\63\1\53\1\65\47\53\1\61\2\63"+
    "\7\53\1\54\1\63\1\64\2\63\43\53\1\66\5\53"+
    "\1\61\1\63\70\0\1\67\5\7\1\0\1\7\7\0"+
    "\26\7\14\0\3\7\1\67\2\0\1\67\1\0\1\70"+
    "\4\10\1\0\1\70\7\0\26\70\11\0\1\71\2\0"+
    "\3\70\5\0\1\70\4\10\1\0\1\70\7\0\5\70"+
    "\1\72\4\70\1\73\5\70\1\74\5\70\11\0\1\71"+
    "\2\0\1\73\1\72\1\74\4\0\1\67\5\7\1\0"+
    "\1\7\7\0\13\7\1\75\12\7\14\0\3\7\1\67"+
    "\2\0\1\67\13\0\1\14\54\0\12\16\1\15\1\14"+
    "\54\16\16\0\1\76\51\0\1\67\5\7\1\0\1\7"+
    "\7\0\1\7\1\77\1\7\1\100\3\7\1\100\13\7"+
    "\1\101\2\7\14\0\3\7\1\67\2\0\2\67\5\7"+
    "\1\0\1\7\7\0\5\7\1\102\20\7\14\0\3\7"+
    "\1\67\2\0\2\67\5\7\1\0\1\7\7\0\10\7"+
    "\1\103\15\7\14\0\3\7\1\67\2\0\2\67\5\7"+
    "\1\0\1\7\7\0\1\104\3\7\1\105\1\106\2\7"+
    "\1\107\15\7\14\0\3\7\1\67\2\0\2\67\5\7"+
    "\1\0\1\7\7\0\1\110\5\7\1\111\17\7\14\0"+
    "\3\7\1\67\2\0\2\67\5\7\1\0\1\7\7\0"+
    "\10\7\1\112\15\7\14\0\3\7\1\67\2\0\2\67"+
    "\5\7\1\0\1\7\7\0\1\7\1\113\5\7\1\114"+
    "\16\7\14\0\3\7\1\67\2\0\2\67\5\7\1\0"+
    "\1\7\7\0\2\7\1\115\23\7\14\0\3\7\1\67"+
    "\2\0\2\67\5\7\1\0\1\7\7\0\6\7\1\116"+
    "\4\7\1\117\12\7\14\0\3\7\1\67\2\0\2\67"+
    "\5\7\1\0\1\7\7\0\4\7\1\120\21\7\14\0"+
    "\3\7\1\67\2\0\2\67\5\7\1\0\1\7\7\0"+
    "\5\7\1\121\2\7\1\122\15\7\14\0\3\7\1\67"+
    "\2\0\2\67\5\7\1\0\1\7\7\0\4\7\1\123"+
    "\13\7\1\124\5\7\14\0\3\7\1\67\2\0\2\67"+
    "\5\7\1\0\1\7\7\0\4\7\1\125\1\126\7\7"+
    "\1\127\10\7\14\0\3\7\1\67\2\0\2\67\5\7"+
    "\1\0\1\7\7\0\6\7\1\130\1\7\1\131\15\7"+
    "\14\0\3\7\1\67\2\0\2\67\5\7\1\0\1\7"+
    "\7\0\15\7\1\132\10\7\14\0\3\7\1\67\2\0"+
    "\2\67\5\7\1\0\1\7\7\0\5\7\1\133\20\7"+
    "\14\0\3\7\1\67\2\0\1\67\51\0\1\134\64\0"+
    "\1\40\2\0\1\134\65\0\1\40\1\0\1\134\67\0"+
    "\1\135\67\0\1\135\1\0\1\50\1\135\64\0\1\135"+
    "\2\0\1\50\73\0\1\136\22\0\1\57\72\0\1\137"+
    "\1\0\1\140\1\55\5\0\1\141\53\0\1\63\72\0"+
    "\1\142\131\0\1\143\7\0\6\67\1\0\1\67\7\0"+
    "\26\67\14\0\4\67\2\0\1\67\1\0\5\70\1\0"+
    "\1\70\7\0\26\70\14\0\3\70\6\0\4\144\63\0"+
    "\2\70\3\145\1\0\1\70\7\0\26\70\14\0\3\70"+
    "\5\0\2\70\2\146\1\70\1\0\1\70\7\0\26\70"+
    "\14\0\3\70\5\0\1\70\4\147\1\0\1\147\7\0"+
    "\3\70\1\147\2\70\1\147\3\70\3\147\11\70\14\0"+
    "\3\70\4\0\1\67\5\7\1\0\1\7\7\0\3\7"+
    "\2\100\21\7\14\0\3\7\1\67\2\0\1\67\16\0"+
    "\1\150\51\0\1\67\5\7\1\0\1\7\7\0\2\7"+
    "\1\151\23\7\14\0\3\7\1\67\2\0\2\67\5\7"+
    "\1\0\1\7\7\0\21\7\1\152\4\7\14\0\3\7"+
    "\1\67\2\0\2\67\5\7\1\0\1\7\7\0\2\7"+
    "\1\112\23\7\14\0\3\7\1\67\2\0\2\67\5\7"+
    "\1\0\1\7\7\0\22\7\1\100\3\7\14\0\3\7"+
    "\1\67\2\0\2\67\5\7\1\0\1\7\7\0\1\7"+
    "\1\153\24\7\14\0\3\7\1\67\2\0\2\67\5\7"+
    "\1\0\1\7\7\0\5\7\1\154\20\7\14\0\3\7"+
    "\1\67\2\0\2\67\5\7\1\0\1\7\7\0\10\7"+
    "\1\100\15\7\14\0\3\7\1\67\2\0\2\67\5\7"+
    "\1\0\1\7\7\0\5\7\1\155\20\7\14\0\3\7"+
    "\1\67\2\0\2\67\5\7\1\0\1\7\7\0\7\7"+
    "\1\156\16\7\14\0\3\7\1\67\2\0\2\67\5\7"+
    "\1\0\1\7\7\0\23\7\1\157\2\7\14\0\3\7"+
    "\1\67\2\0\2\67\5\7\1\0\1\112\7\0\26\7"+
    "\14\0\3\7\1\67\2\0\2\67\5\7\1\0\1\7"+
    "\7\0\7\7\1\160\16\7\14\0\3\7\1\67\2\0"+
    "\2\67\5\7\1\0\1\7\7\0\10\7\1\161\15\7"+
    "\14\0\3\7\1\67\2\0\2\67\5\7\1\0\1\7"+
    "\7\0\1\162\25\7\14\0\3\7\1\67\2\0\2\67"+
    "\5\7\1\0\1\7\7\0\2\7\1\163\23\7\14\0"+
    "\3\7\1\67\2\0\2\67\5\7\1\0\1\7\7\0"+
    "\5\7\1\164\20\7\14\0\3\7\1\67\2\0\2\67"+
    "\5\7\1\0\1\7\7\0\5\7\1\165\20\7\14\0"+
    "\3\7\1\67\2\0\2\67\5\7\1\0\1\7\7\0"+
    "\13\7\1\166\12\7\14\0\3\7\1\67\2\0\2\67"+
    "\5\7\1\0\1\7\7\0\1\167\6\7\1\170\16\7"+
    "\14\0\3\7\1\67\2\0\2\67\5\7\1\0\1\7"+
    "\7\0\13\7\1\171\1\172\11\7\14\0\3\7\1\67"+
    "\2\0\2\67\5\7\1\0\1\7\7\0\6\7\1\173"+
    "\17\7\14\0\3\7\1\67\2\0\2\67\5\7\1\0"+
    "\1\7\7\0\1\7\1\174\24\7\14\0\3\7\1\67"+
    "\2\0\2\67\5\7\1\0\1\7\7\0\6\7\1\175"+
    "\17\7\14\0\3\7\1\67\2\0\2\67\5\7\1\0"+
    "\1\7\7\0\7\7\1\176\16\7\14\0\3\7\1\67"+
    "\2\0\2\67\5\7\1\0\1\7\7\0\1\177\25\7"+
    "\14\0\3\7\1\67\2\0\2\67\5\7\1\0\1\7"+
    "\7\0\1\200\25\7\14\0\3\7\1\67\2\0\2\67"+
    "\5\7\1\0\1\7\7\0\1\7\1\170\24\7\14\0"+
    "\3\7\1\67\2\0\1\67\60\0\1\201\25\0\1\202"+
    "\131\0\1\202\7\0\1\67\5\7\1\0\1\7\7\0"+
    "\5\7\1\203\20\7\14\0\3\7\1\67\2\0\2\67"+
    "\5\7\1\0\1\7\7\0\6\7\1\204\17\7\14\0"+
    "\3\7\1\67\2\0\2\67\5\7\1\0\1\7\7\0"+
    "\6\7\1\156\17\7\14\0\3\7\1\67\2\0\2\67"+
    "\5\7\1\0\1\7\7\0\23\7\1\100\2\7\14\0"+
    "\3\7\1\67\2\0\2\67\5\7\1\0\1\7\7\0"+
    "\12\7\1\205\13\7\14\0\3\7\1\67\2\0\2\67"+
    "\5\7\1\0\1\7\7\0\13\7\1\203\12\7\14\0"+
    "\3\7\1\67\2\0\2\67\5\7\1\0\1\7\7\0"+
    "\1\206\25\7\14\0\3\7\1\67\2\0\2\67\5\7"+
    "\1\0\1\7\7\0\7\7\1\170\16\7\14\0\3\7"+
    "\1\67\2\0\2\67\5\7\1\0\1\7\7\0\17\7"+
    "\1\207\6\7\14\0\3\7\1\67\2\0\2\67\5\7"+
    "\1\0\1\7\7\0\12\7\1\210\13\7\14\0\3\7"+
    "\1\67\2\0\2\67\5\7\1\0\1\7\7\0\4\7"+
    "\1\211\21\7\14\0\3\7\1\67\2\0\2\67\5\7"+
    "\1\0\1\7\7\0\6\7\1\212\17\7\14\0\3\7"+
    "\1\67\2\0\2\67\5\7\1\0\1\7\7\0\3\7"+
    "\1\100\22\7\14\0\3\7\1\67\2\0\2\67\5\7"+
    "\1\0\1\7\7\0\13\7\1\100\12\7\14\0\3\7"+
    "\1\67\2\0\2\67\5\7\1\0\1\7\7\0\14\7"+
    "\1\100\11\7\14\0\3\7\1\67\2\0\2\67\5\7"+
    "\1\0\1\7\7\0\13\7\1\213\12\7\14\0\3\7"+
    "\1\67\2\0\2\67\5\7\1\0\1\7\7\0\7\7"+
    "\1\214\16\7\14\0\3\7\1\67\2\0\2\67\5\7"+
    "\1\0\1\7\7\0\2\7\1\215\23\7\14\0\3\7"+
    "\1\67\2\0\2\67\5\7\1\0\1\7\7\0\10\7"+
    "\1\151\15\7\14\0\3\7\1\67\2\0\2\67\5\7"+
    "\1\0\1\7\7\0\7\7\1\100\16\7\14\0\3\7"+
    "\1\67\2\0\2\67\5\7\1\0\1\7\7\0\1\7"+
    "\1\216\24\7\14\0\3\7\1\67\2\0\2\67\5\7"+
    "\1\0\1\7\7\0\4\7\1\170\21\7\14\0\3\7"+
    "\1\67\2\0\2\67\5\7\1\0\1\7\7\0\10\7"+
    "\1\216\15\7\14\0\3\7\1\67\2\0\2\67\5\7"+
    "\1\0\1\7\7\0\4\7\1\217\21\7\14\0\3\7"+
    "\1\67\2\0\2\67\5\7\1\0\1\220\7\0\26\7"+
    "\14\0\3\7\1\67\2\0\2\67\5\7\1\0\1\7"+
    "\7\0\1\7\1\221\24\7\14\0\3\7\1\67\2\0"+
    "\2\67\5\7\1\0\1\7\7\0\10\7\1\222\15\7"+
    "\14\0\3\7\1\67\2\0\2\67\5\7\1\0\1\7"+
    "\7\0\6\7\1\223\17\7\14\0\3\7\1\67\2\0"+
    "\2\67\5\7\1\0\1\7\7\0\13\7\1\224\12\7"+
    "\14\0\3\7\1\67\2\0\2\67\5\7\1\0\1\7"+
    "\7\0\16\7\1\100\7\7\14\0\3\7\1\67\2\0"+
    "\2\67\5\7\1\0\1\7\7\0\21\7\1\216\4\7"+
    "\14\0\3\7\1\67\2\0\2\67\5\7\1\0\1\7"+
    "\7\0\7\7\1\225\16\7\14\0\3\7\1\67\2\0"+
    "\2\67\5\7\1\0\1\7\7\0\1\226\25\7\14\0"+
    "\3\7\1\67\2\0\2\67\5\7\1\0\1\7\7\0"+
    "\2\7\1\100\23\7\14\0\3\7\1\67\2\0\2\67"+
    "\5\7\1\0\1\7\7\0\4\7\1\103\21\7\14\0"+
    "\3\7\1\67\2\0\2\67\5\7\1\0\1\7\7\0"+
    "\6\7\1\100\17\7\14\0\3\7\1\67\2\0\2\67"+
    "\5\7\1\0\1\7\7\0\11\7\1\151\14\7\14\0"+
    "\3\7\1\67\2\0\2\67\5\7\1\0\1\7\7\0"+
    "\1\7\1\100\24\7\14\0\3\7\1\67\2\0\2\67"+
    "\5\7\1\0\1\7\7\0\4\7\1\100\21\7\14\0"+
    "\3\7\1\67\2\0\2\67\5\7\1\0\1\7\7\0"+
    "\6\7\1\227\17\7\14\0\3\7\1\67\2\0\2\67"+
    "\5\7\1\0\1\7\7\0\1\7\1\230\24\7\14\0"+
    "\3\7\1\67\2\0\2\67\5\7\1\0\1\7\7\0"+
    "\1\7\1\151\24\7\14\0\3\7\1\67\2\0\2\67"+
    "\5\7\1\0\1\7\7\0\17\7\1\170\6\7\14\0"+
    "\3\7\1\67\2\0\1\67";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6832];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\1\11\3\1\1\11\1\1\1\11\26\1\1\11"+
    "\4\1\2\11\1\1\3\11\1\1\2\11\1\1\2\11"+
    "\5\1\1\0\4\1\1\0\35\1\2\11\1\0\3\11"+
    "\2\0\4\1\1\11\30\1\2\11\26\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //esto se copia directamente

    StringBuffer string = new StringBuffer();
    Boolean cambioLinea = false;

    public String lexeme;
    public int getLine(){
        return yyline;
    }

    private Symbol symbol(int type) {
        return new Symbol(type, yyline+1, yyline+1);
    }
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline+1, yyline+1, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 224) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case MYSTRING: {
              yybegin(YYINITIAL); lexeme = "String sin terminar: " + string.toString(); return symbol(sym.ERROR);
            }
            case 153: break;
            case MYCHAR: {
              yybegin(YYINITIAL); lexeme = "Char sin terminar: " + string.toString(); return symbol(sym.ERROR);
            }
            case 154: break;
            case COMENTARIOBLOQUE: {
              yybegin(YYINITIAL); lexeme = "Comentario de bloque sin terminar: " + "\"\"\"" + string.toString(); return symbol(sym.ERROR, lexeme);
            }
            case 155: break;
            case COMENTARIOBLOQUE2: {
              yybegin(YYINITIAL); lexeme = "Comentario de bloque sin terminar: " + "\'\'\'" + string.toString(); return symbol(sym.ERROR, lexeme);
            }
            case 156: break;
            default:
          {   return new java_cup.runtime.Symbol(sym.EOF);
 }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexeme = yytext();return symbol(sym.ERROR, lexeme);
            }
          case 33: break;
          case 2: 
            { lexeme=yytext(); return symbol(sym.identificador, lexeme);
            }
          case 34: break;
          case 3: 
            { lexeme=yytext(); return symbol(sym.INT, lexeme);
            }
          case 35: break;
          case 4: 
            { lexeme = yytext(); return symbol(sym.opDelimitadores, lexeme);
            }
          case 36: break;
          case 5: 
            { /* ignore */
            }
          case 37: break;
          case 6: 
            { string.setLength(0); cambioLinea = false; yybegin(MYSTRING);
            }
          case 38: break;
          case 7: 
            { lexeme = yytext(); return symbol(sym.opAritmeticos, lexeme);
            }
          case 39: break;
          case 8: 
            { lexeme = yytext(); return symbol(sym.opAsignaciones, lexeme);
            }
          case 40: break;
          case 9: 
            { lexeme = yytext(); return symbol(sym.opComparadores, lexeme);
            }
          case 41: break;
          case 10: 
            { lexeme = yytext(); return symbol(sym.opBits, lexeme);
            }
          case 42: break;
          case 11: 
            { lexeme = yytext(); return symbol(sym.dosPuntos, lexeme);
            }
          case 43: break;
          case 12: 
            { string.setLength(0); yybegin(MYCHAR);
            }
          case 44: break;
          case 13: 
            { string.append( yytext() );
            }
          case 45: break;
          case 14: 
            { string.append(' ');
            }
          case 46: break;
          case 15: 
            { string.append('\t');
            }
          case 47: break;
          case 16: 
            { cambioLinea = true; string.append('\n');
            }
          case 48: break;
          case 17: 
            { yybegin(YYINITIAL);
                                     lexeme = "\"" +string.toString()+"\"";
                                     if(cambioLinea){
                                          return symbol(sym.ERROR, lexeme);
                                     }else{
                                          return symbol(sym.STRING, lexeme);
                                     }
            }
          case 49: break;
          case 18: 
            { yybegin(YYINITIAL); lexeme = "'"+ string.toString()+"'"; 
                                     if(string.length()>1)
                                        return symbol(sym.ERROR, lexeme);
                                     else
                                        return symbol(sym.CHAR, lexeme);
            }
          case 50: break;
          case 19: 
            { string.append(yytext());
            }
          case 51: break;
          case 20: 
            { lexeme=yytext(); return symbol(sym.ERROR, lexeme);
            }
          case 52: break;
          case 21: 
            { lexeme = yytext(); return symbol(sym.INT, lexeme);
            }
          case 53: break;
          case 22: 
            { lexeme = yytext(); return symbol(sym.palabraReservada, lexeme);
            }
          case 54: break;
          case 23: 
            { lexeme = yytext(); return symbol(sym.opLogicos, lexeme);
            }
          case 55: break;
          case 24: 
            { string.append('\"');
            }
          case 56: break;
          case 25: 
            { string.append('\n');
            }
          case 57: break;
          case 26: 
            { string.append('\r');
            }
          case 58: break;
          case 27: 
            { lexeme=yytext(); return symbol(sym.FLOAT, lexeme);
            }
          case 59: break;
          case 28: 
            { string.setLength(0); yybegin(COMENTARIOBLOQUE);
            }
          case 60: break;
          case 29: 
            { lexeme = yytext(); return symbol(sym.var, lexeme);
            }
          case 61: break;
          case 30: 
            { string.setLength(0); yybegin(COMENTARIOBLOQUE2);
            }
          case 62: break;
          case 31: 
            { yybegin(YYINITIAL);
            }
          case 63: break;
          case 32: 
            { lexeme = yytext(); return symbol(sym.clas, lexeme);
            }
          case 64: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
